### ISSUE TITLE
Right clicking with the cursor does not select the secondary coords

### ISSUE THREAD

**Issue by Apollucas** [raccoonasdf/bunyedit#21] opened 2024-08-26 16:54 UTC
The title says it all

**Comment by raccoonasdf** [comment] 2024-08-26 18:31
can't reproduce :(

which mod version? BTA 7.1 or 7.2? singleplayer or multiplayer?

**Comment by Apollucas** [comment] 2024-08-26 19:54
Oh right, sorry, I should be more specific; I'm running BTA 7.2_01 in a singleplayer world. The mod works fine other than this quirk, though.

**Comment by raccoonasdf** [comment] 2024-08-26 20:26
right clicking does *nothing*, right? not some strange other behavior? no error message in chat?

are the results the same whether you're selecting from within normal block breaking distance or not?

i tested out both BTA 7.2 and 7.2_01 and it works fine for me, so unfortunately i don't really have any leads to follow. it's a long shot, given that i don't *think* i changed anything relevant, but you could give [the build i just pushed](https://github.com/raccoonasdf/bunyedit/actions/runs/10566579152/artifacts/1856384859) a shot, i suppose!

**Comment by Apollucas** [comment] 2024-08-27 09:49
Correct! There's no errors or odd behaviour, regardless of distance from the block.

When running your new build, though, I do get an error, this is it:
```
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: org/jparsec/error/ParserException
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:483)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.legacy.LegacyLauncher.launch(LegacyLauncher.java:123)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: org/jparsec/error/ParserException
	at fun.raccoon.bunyedit.command.EditorCommandBuilder.build(EditorCommandBuilder.java:61)
	at fun.raccoon.bunyedit.command.EditorCommands.<clinit>(EditorCommands.java:17)
	at net.minecraft.core.net.command.Commands.handler$zza000$bunyedit$initMyCommands(Commands.java:521)
	at net.minecraft.core.net.command.Commands.initCommands(Commands.java:38)
	at net.minecraft.core.net.command.Commands.initClientCommands(Commands.java:62)
	at net.minecraft.core.net.command.ClientCommandHandler.<init>(ClientCommandHandler.java:15)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:218)
	at net.minecraft.client.Minecraft.startMainThread(Minecraft.java:2359)
	at net.minecraft.client.Minecraft.main(Minecraft.java:2389)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:478)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.jparsec.error.ParserException
	at java.lang.ClassLoader.findClass(ClassLoader.java:523)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more
```
Just to be sure, I only ran the build with HalpLibe and ModMenu as other mods.

By the way, I really appreciate the swift responses, I hope I'm not being a bother. :)

**Comment by raccoonasdf** [comment] 2024-08-27 15:40
oops! oversight on my part. i didn't embed the jparsec library in the jar because i already have it. [fixed in 0.7.3](https://github.com/raccoonasdf/bunyedit/releases/tag/0.7.3)

**Comment by Apollucas** [comment] 2024-08-27 17:46
It now works perfectly! Thanks a lot :))

**Comment by raccoonasdf** [comment] 2024-08-27 20:03
yay!! no problem :)

**Closed as completed by raccoonasdf** 2024-08-27 20:03 UTC
